-
  name: "Example project"
  notification: slack
  logo: images/logos/example.png
  members:
    - UEMA8DE9Y
    - UEN897F5U
-
  name: "Bar"
  notification: email
  logo: images/logos/bar.png
  members:
    - bar@example.com
